[View in Colaboratory](https://colab.research.google.com/github/romth777/ML-Basics/blob/master/src/titanic_survivals.ipynb)

# タイタニック号生存者予測

全般を通して、こちらを参考にしました。
https://qiita.com/suzumi/items/8ce18bc90c942663d1e6

欠損データの取り扱いはこちらのkernelを参考にしました
https://www.kaggle.com/ldfreeman3/a-data-science-framework-to-achieve-99-accuracy

## おまじない☆彡

In [0]:
# !pip install pathlib
from pathlib import Path
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder

## データの読み込み

In [6]:
# show upload dialog
from google.colab import files
uploaded = files.upload()

Saving test.csv to test.csv
Saving train.csv to train.csv


In [0]:
# train_path = Path('../data/titanic/train.csv')
# test_path = Path('../data/titanic/test.csv')
train_path = Path('./train.csv')
test_path = Path('./test.csv')
_train_data = pd.read_csv(train_path)
_test_data = pd.read_csv(test_path)

## データを眺める

In [9]:
_train_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [10]:
_train_data.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

## 欠損データの取り扱い

In [11]:
_train_data.isnull().any()

PassengerId    False
Survived       False
Pclass         False
Name           False
Sex            False
Age             True
SibSp          False
Parch          False
Ticket         False
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [12]:
nan_age = _train_data.Age.median()
train_data = _train_data.copy()
train_data["Age"].fillna(nan_age, inplace=True)
train_data.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  891.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.361582    0.523008   
std     257.353842    0.486592    0.836071   13.019697    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   22.000000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   35.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [13]:
nan_embarked = train_data['Embarked'].mode()[0]
train_data['Embarked'].fillna(nan_embarked, inplace = True)

nan_fare = train_data['Fare'].median()
train_data['Fare'].fillna(nan_fare, inplace = True)
    
drop_column = ['Name', 'PassengerId', 'Cabin', 'Ticket']
train_data.drop(drop_column, axis=1, inplace = True)
train_data.describe()

Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  891.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.361582    0.523008    0.381594   32.204208
std      0.486592    0.836071   13.019697    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   22.000000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   35.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [14]:
train_data.isnull().any()

Survived    False
Pclass      False
Sex         False
Age         False
SibSp       False
Parch       False
Fare        False
Embarked    False
dtype: bool

In [15]:
_test_data.describe()

PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

In [16]:
test_data = _test_data.copy()
test_data["Age"].fillna(nan_age, inplace=True)
test_data['Embarked'].fillna(nan_embarked, inplace = True)
test_data['Fare'].fillna(nan_fare, inplace = True)
test_data.drop(drop_column, axis=1, inplace = True)
test_data.head()

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       3    male  34.5      0      0   7.8292        Q
1       3  female  47.0      1      0   7.0000        S
2       2    male  62.0      0      0   9.6875        Q
3       3    male  27.0      0      0   8.6625        S
4       3  female  22.0      1      1  12.2875        S

In [17]:
test_data.isnull().any()

Pclass      False
Sex         False
Age         False
SibSp       False
Parch       False
Fare        False
Embarked    False
dtype: bool

In [18]:
label = LabelEncoder()
train_data['Sex_Code'] = label.fit_transform(train_data['Sex'])
train_data['Embarked_Code'] = label.fit_transform(train_data['Embarked'])
train_data = train_data.drop(['Sex', 'Embarked'], axis=1)
test_data['Sex_Code'] = label.fit_transform(test_data['Sex'])
test_data['Embarked_Code'] = label.fit_transform(test_data['Embarked'])
test_data = test_data.drop(['Sex', 'Embarked'], axis=1)
train_data.head()

Survived  Pclass   Age  SibSp  Parch     Fare  Sex_Code  Embarked_Code
0         0       3  22.0      1      0   7.2500         1              2
1         1       1  38.0      1      0  71.2833         0              0
2         1       3  26.0      0      0   7.9250         0              2
3         1       1  35.0      1      0  53.1000         0              2
4         0       3  35.0      0      0   8.0500         1              2

## データの整形

In [19]:
x_train = train_data.drop('Survived', axis=1)
y_train = train_data.Survived
x_train.head()

Pclass   Age  SibSp  Parch     Fare  Sex_Code  Embarked_Code
0       3  22.0      1      0   7.2500         1              2
1       1  38.0      1      0  71.2833         0              0
2       3  26.0      0      0   7.9250         0              2
3       1  35.0      1      0  53.1000         0              2
4       3  35.0      0      0   8.0500         1              2

In [20]:
x_train = x_train.values
y_train = y_train.values
print(x_train)

[[ 3.     22.      1.     ...  7.25    1.      2.    ]
 [ 1.     38.      1.     ... 71.2833  0.      0.    ]
 [ 3.     26.      0.     ...  7.925   0.      2.    ]
 ...
 [ 3.     28.      1.     ... 23.45    0.      2.    ]
 [ 1.     26.      0.     ... 30.      1.      0.    ]
 [ 3.     32.      0.     ...  7.75    1.      1.    ]]


In [21]:
x_test = test_data.values
print(x_test)

[[ 3.     34.5     0.     ...  7.8292  1.      1.    ]
 [ 3.     47.      1.     ...  7.      0.      2.    ]
 [ 2.     62.      0.     ...  9.6875  1.      1.    ]
 ...
 [ 3.     38.5     0.     ...  7.25    1.      2.    ]
 [ 3.     28.      0.     ...  8.05    1.      2.    ]
 [ 3.     28.      1.     ... 22.3583  1.      0.    ]]


## 学習

In [0]:
model = RandomForestClassifier(n_estimators = 100)

In [23]:
model.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

## 予測

In [24]:
model.predict(x_test)

array([0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
_x_train, _x_test, _y_train, _y_test = train_test_split(x_train, y_train, test_size=0.33, random_state=42)

In [28]:
model.fit(_x_train, _y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [29]:
print('score:{:.2f}%'.format(model.score(_x_test, _y_test) * 100))

score:77.97%


## 教師なし：k-meansクラスタリング

In [0]:
from sklearn.cluster import KMeans

In [0]:
kmeans = KMeans(n_clusters=2, random_state=0).fit(_x_train)

In [38]:
x_pred = kmeans.predict(_x_test)
x_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [36]:
_y_test

array([1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0])

In [40]:
tp, tn, fp, fn = 0, 0, 0, 0
for x_item, y_item in zip(x_pred, _y_test):
  if x_item == 1 and y_item == 1:
    tp += 1
  elif x_item == 0 and y_item == 0:
    tn += 1
  elif x_item == 1 and y_item == 0:
    fp += 1
  elif x_item == 0 and y_item == 1:
    fn += 1
tp, tn, fp, fn

(11, 171, 4, 109)

In [44]:
accuracy = float(tp + tn) / (tp + tn + fp + fn) # 精度
precision = float(tp) / (tp + fp) # 適合率：高いとデータの間違いが少ない
recall = float(tp) / (tp + fn) # 再現率：高いとデータの取りこぼしが少ない
f_score = float(2 * recall * precision) / (recall + precision) # 調和平均
accuracy, precision, recall, f_score

(0.6169491525423729,
 0.7333333333333333,
 0.09166666666666666,
 0.16296296296296295)

## 教師なし：PCA

In [0]:
from sklearn.decomposition import PCA

In [54]:
_x_train.shape

(596, 7)

In [59]:
pca = PCA(n_components=5)
x_train_pca = pca.fit_transform(_x_train)
x_train_pca.shape

(596, 5)

In [60]:
model = RandomForestClassifier(n_estimators = 100)
model.fit(x_train_pca, _y_train)
x_test_pca = pca.transform(_x_test)
print('score:{:.2f}%'.format(model.score(x_test_pca, _y_test) * 100))

score:72.54%
